### ISSUE TITLE
Foreign characters (title error)

### ISSUE THREAD

**Issue by zelik888** [Dannyman3819/Automatic-Youtube-Downloader#11]
As the code is, it has problems dealing with subscriptions that have foreign characters in the subscription feed. 
my subscription_manager.xml looks like:
`<opml version="1.1">
<body><outline text="YouTube Subscriptions" title="YouTube Subscriptions"><outline text="巧虎成長版" title="巧虎成長版" type="rss" xmlUrl="https://www.youtube.com/feeds/videos.xml?channel_id=UC95-4AS4gi-AULU4e10IkAw" /><outline text="buycartv" title="buycartv" type="rss" xmlUrl="https://www.youtube.com/feeds/videos.xml?channel_id=UC-MByr5LRnWmVN94Ija4XJg" /></outline></body></opml>`

`
Parsing Youtube data.....
Would you like to select which channels you want to include, or do you want to include all of them?
If you include all channels you can remove them manually by editing data/youtubeData.xml and deleting the entire line of the channel you do not want (Choose this option if you have a lot of subscriptions)
Enter 'all' to keep all subscriptions or 'select' to select which channels (or 'a' or 's'):a
Including all channels

Video 1/2
Traceback (most recent call last):
  File "setup.py", line 301, in <module>
    main()
  File "setup.py", line 290, in main
    channel_selection()
  File "setup.py", line 163, in channel_selection
    print(title)
  File "C:\Users\Victor\AppData\Local\Programs\Python\Python35-32\lib\encodings\cp437.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-4: character maps to <undefined>
`

**Comment by PizzaWaffles** [comment]
Working on a fix now. The updated setup.py should take care of non utf-8 characters. I still need to work on main.py to remove non utf-8 characters.

**Comment by pappabetalar** [comment]
Hi

I'm having similar problems, after i enter "s" to select channel the program quits.


`Traceback (most recent call last):
  File "setup.py", line 264, in <module>
    main()
  File "setup.py", line 249, in main
    channel_selection()
  File "setup.py", line 114, in channel_selection
    title = bytes(channel.title, 'utf-8').decode('utf-8', 'ignore')
TypeError: str() takes at most 1 argument (2 given)
tian@BIGubuntu:~/Automatic-Youtube-Downloader-master$

I am running the latest version downloaded right before writing this on Ubuntu 18.04
![ayd](https://user-images.githubusercontent.com/11709536/45139673-ce66bc80-b1b0-11e8-8203-4fabb1af5b23.png)

`

**Comment by zelik888** [comment]
Thank you! Would this eliminate all the Chinese characters then? I was
hoping it could preserve it...

-- 
Victor Lee

**Comment by PizzaWaffles** [comment]
Please download the newest main.py and setup.py, just pushed a change that should fix this.

**Comment by zelik888** [comment]
Now it won't crash out on Chinese videos but it won't download either.
here's console log:
`Be
[youtube] 9etwdg_AZEI: Downloading webpage
[youtube] 9etwdg_AZEI: Downloading video info webpage
[youtube] 9etwdg_AZEI: Downloading js player vflvABTsY
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\Victor\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1210, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\Victor\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1121, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "C:\Users\Victor\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1182, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "C:\Users\Victor\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\common.py", line 972, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Failed to Download
[youtube] 7Rp9mAhfcK0: Downloading webpage
[youtube] 7Rp9mAhfcK0: Downloading video info webpage
[youtube] 7Rp9mAhfcK0: Downloading js player vflvABTsY
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\Victor\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1210, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\Victor\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1121, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "C:\Users\Victor\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1182, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "C:\Users\Victor\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\common.py", line 972, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Failed to Download
[youtube] XzRZAxRNyNU: Downloading webpage
[youtube] XzRZAxRNyNU: Downloading video info webpage
[youtube] XzRZAxRNyNU: Downloading js player vflvABTsY
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\Victor\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1210, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\Victor\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1121, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "C:\Users\Victor\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1182, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "C:\Users\Victor\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\common.py", line 972, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Failed to Download
[youtube] l6uWG6Vi2a8: Downloading webpage
[youtube] l6uWG6Vi2a8: Downloading video info webpage
[youtube] l6uWG6Vi2a8: Downloading js player vflvABTsY
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\Victor\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1210, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\Victor\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1121, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "C:\Users\Victor\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1182, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "C:\Users\Victor\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\common.py", line 972, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Failed to Download
[youtube] Lypv06Gr0v4: Downloading webpage
[youtube] Lypv06Gr0v4: Downloading video info webpage
[youtube] Lypv06Gr0v4: Downloading js player vflvABTsY
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\Victor\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1210, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\Victor\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1121, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "C:\Users\Victor\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1182, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "C:\Users\Victor\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\common.py", line 972, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Failed to Download`

This is from subscription to this channel: https://www.youtube.com/channel/UC5RIj1FcKvZ1R2Vx2wWKDTg

**Comment by PizzaWaffles** [comment]
First issue is Youtube updated some stuff so make sure youtube-dl is up to date run these.
`pip uninstall youtube-dl`
`pip install youtube-dl`


Second issue isn't really an issue but the foreign characters were just getting removed. I changed some stuff to allow the foreign characters to stay. So update just main.py
