### ISSUE TITLE
crashing when subscription feed contains yet to broadcast live stream

### ISSUE THREAD

**Issue by zelik888** [Dannyman3819/Automatic-Youtube-Downloader#12]
here is the copy of subscription_manager.xml
`<opml version="1.1">
<body><outline text="YouTube Subscriptions" title="YouTube Subscriptions"><outline text="SweViver" title="SweViver" type="rss" xmlUrl="https://www.youtube.com/feeds/videos.xml?channel_id=UCQ33TPQYw_-c6itr0ReIu-Q" /></outline></body></opml>
`
Here is a log, the video is not available because it's a yet to broadcast livestream.

`Checking line API_KEY=[REDACTED] as API_KEY = [REDACTED]
Checking line SCHEDULING_MODE=DELAY as SCHEDULING_MODE = DELAY
Checking line SCHEDULING_MODE_VALUE=5 as SCHEDULING_MODE_VALUE = 5
Checking line NUM_VIDEOS=15 as NUM_VIDEOS = 15
Checking line DESTINATION_FOLDER=Z:\Youtube\ as DESTINATION_FOLDER = Z:\Youtube\
Starting on run number 0
Evaluating delay schedule mode
  First run, doing it now
Sleeping for 0 minutes...

SweViver
Downloading - LIVE Q&A: Pimax 8K & 5K+ Info & Release Date, Backer Meetup summary and more!  |  yt:video:ecR3JCUaeZ0
Channel - SweViver  |  UCQ33TPQYw_-c6itr0ReIu-Q
[youtube] ecR3JCUaeZ0: Downloading webpage
[youtube] ecR3JCUaeZ0: Downloading video info webpage
ERROR: This video is unavailable.
Failed to Download
Error dump in error.log
Traceback (most recent call last):
  File "C:\Users\Victor\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "C:\Users\Victor\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\common.py", line 502, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\Victor\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1886, in _real_extract
    raise ExtractorError(error_message, expected=True)
youtube_dl.utils.ExtractorError: This video is unavailable.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 323, in main
    info_dict = ydl.extract_info(url, download=False)
  File "C:\Users\Victor\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 815, in extract_info
    self.report_error(compat_str(e), e.format_traceback())
  File "C:\Users\Victor\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 620, in report_error
    self.trouble(error_message, tb)
  File "C:\Users\Victor\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 590, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: This video is unavailable.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 387, in <module>
    main()
  File "main.py", line 345, in main
    pprint(locals(), stream=f)
  File "C:\Users\Victor\AppData\Local\Programs\Python\Python35-32\lib\pprint.py", line 53, in pprint
    printer.pprint(object)
  File "C:\Users\Victor\AppData\Local\Programs\Python\Python35-32\lib\pprint.py", line 139, in pprint
    self._format(object, self._stream, 0, 0, {}, 0)
  File "C:\Users\Victor\AppData\Local\Programs\Python\Python35-32\lib\pprint.py", line 167, in _format
    p(self, object, stream, indent, allowance, context, level + 1)
  File "C:\Users\Victor\AppData\Local\Programs\Python\Python35-32\lib\pprint.py", line 189, in _pprint_dict
    context, level)
  File "C:\Users\Victor\AppData\Local\Programs\Python\Python35-32\lib\pprint.py", line 346, in _format_dict_items
    context, level)
  File "C:\Users\Victor\AppData\Local\Programs\Python\Python35-32\lib\pprint.py", line 176, in _format
    stream.write(rep)
  File "C:\Users\Victor\AppData\Local\Programs\Python\Python35-32\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u25ba' in position 2313: character maps to <undefined>`

**Comment by PizzaWaffles** [comment]
Thanks working on a fix now.

**Comment by Dannyman3819** [comment]
Should be fixed with newest update
