### ISSUE TITLE
Chinese language / foreign characters.

### ISSUE THREAD

**Issue by zelik888** [Dannyman3819/Automatic-Youtube-Downloader#20]
Everything works but the filenames are not being written in UTF-8, getting gibberish.
![screen shot 2018-09-18 at 8 32 03 am](https://user-images.githubusercontent.com/32435275/45657560-7cf9ee00-bb1d-11e8-8bb8-5a4affd12919.png)

**Comment by zelik888** [comment]
It seems the error still exists,
`C:\Automatic-Youtube-Downloader>python3 main.py
Starting on run number 0
Downloading Icons....






Complete.
Qiaohu
[youtube] 9etwdg_AZEI: Downloading webpage
[youtube] 9etwdg_AZEI: Downloading video info webpage
[youtube] 9etwdg_AZEI: Downloading js player vflkUTZn2
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\Victor\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1210, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\Victor\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1121, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "C:\Users\Victor\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1182, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "C:\Users\Victor\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\common.py", line 972, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Failed to Download
[youtube] 7Rp9mAhfcK0: Downloading webpage
[youtube] 7Rp9mAhfcK0: Downloading video info webpage
[youtube] 7Rp9mAhfcK0: Downloading js player vflkUTZn2
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\Victor\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1210, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\Victor\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1121, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "C:\Users\Victor\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1182, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "C:\Users\Victor\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\common.py", line 972, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Failed to Download
[youtube] XzRZAxRNyNU: Downloading webpage
[youtube] XzRZAxRNyNU: Downloading video info webpage
[youtube] XzRZAxRNyNU: Downloading js player vflkUTZn2
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\Victor\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1210, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\Victor\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1121, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "C:\Users\Victor\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1182, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "C:\Users\Victor\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\common.py", line 972, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Failed to Download
[youtube] l6uWG6Vi2a8: Downloading webpage
[youtube] l6uWG6Vi2a8: Downloading video info webpage
[youtube] l6uWG6Vi2a8: Downloading js player vflkUTZn2
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\Victor\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1210, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\Victor\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1121, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "C:\Users\Victor\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1182, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "C:\Users\Victor\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\common.py", line 972, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Failed to Download
[youtube] Lypv06Gr0v4: Downloading webpage
[youtube] Lypv06Gr0v4: Downloading video info webpage
[youtube] Lypv06Gr0v4: Downloading js player vflkUTZn2
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\Victor\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1210, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\Victor\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1121, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "C:\Users\Victor\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1182, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "C:\Users\Victor\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\common.py", line 972, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Failed to Download`

**Comment by PizzaWaffles** [comment]
Just tested it in windows command prompt and its an issue with cmd not being able to print out foreign characters, see here
<img width="663" alt="capture" src="https://user-images.githubusercontent.com/1672697/45664151-44c3c280-babf-11e8-8ba9-35b370170ee4.PNG">

I tested it again in my development ide and it prints fine. 
<img width="847" alt="capture" src="https://user-images.githubusercontent.com/1672697/45663793-25c43100-babd-11e8-935a-a5fcaf37dd3c.PNG">
This just means it'l print the correct chracters to the file.


For you exception error I found this while searching 
[https://github.com/rg3/youtube-dl/issues/4232](https://github.com/rg3/youtube-dl/issues/4232)

Try a clean install of everything here, and make sure you update youtube-dl. Let me know if anything works for you.

**Comment by zelik888** [comment]
you are absolutely right, thank you. I had updated youtube on my python 2.7 but not on my python 3, closed. thank you for this!
