### ISSUE TITLE
Issue with account

### ISSUE THREAD

**Issue by DrDinosaur** [Dannyman3819/Automatic-Youtube-Downloader#49]
I'm unable to get the account feature to work. I get "There was something wrong with your key, please check the setup.log" My API key and channel ID look fine. Google is showing the API key has some use too, I tried a few keys. 

> 12/21/2019 02:47:49 AM Program setup.py started
12/21/2019 02:47:54 AM get_API_key_config function called
12/21/2019 02:47:54 AM get_sub_list function called
12/21/2019 02:52:42 AM Program setup.py started
12/21/2019 02:52:48 AM add_channel function called
12/21/2019 02:54:39 AM add_channel function called
12/21/2019 02:55:57 AM At main menu, user selected option 1
12/21/2019 02:55:57 AM install_dependencies function called
12/21/2019 02:55:58 AM get_API_key function called
12/21/2019 02:55:58 AM Gathering API key info
12/21/2019 02:56:11 AM Google API Key returned 200 (success)
12/21/2019 02:56:11 AM get_sub_list function called
12/21/2019 02:56:35 AM ERROR: My Channel Key incorrect
12/21/2019 02:56:35 AM ERRORHTTP Error 403: Forbidden
12/21/2019 02:56:35 AM Traceback (most recent call last):
  File "setup.py", line 575, in get_sub_list
    url_data = urlopen(
  File "C:\Program Files\Python38\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Program Files\Python38\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "C:\Program Files\Python38\lib\urllib\request.py", line 640, in http_response
    response = self.parent.error(
  File "C:\Program Files\Python38\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "C:\Program Files\Python38\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "C:\Program Files\Python38\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by ghost** [comment]
This issue can be fixed by making you subscriptions public. On the YouTube support site is a good step by step guide: [https://support.google.com/youtube/answer/7280190](https://support.google.com/youtube/answer/7280190 )
