### ISSUE TITLE
Installing requirements throws an exception

### ISSUE THREAD

**Issue by atrus05** [Dannyman3819/Automatic-Youtube-Downloader#5]
Going through the install process on my Ubuntu 14.04 rig and running into an issue when running the requirements.txt install line:
```
atrus@norco:~/Automatic-Youtube-Downloader$ pip install -r requirements.txt
Requirement already satisfied (use --upgrade to upgrade): beautifulsoup4 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 1))
Downloading/unpacking listparser (from -r requirements.txt (line 2))
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1198, in prepare_files
    do_download,
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1376, in unpack_url
    self.session,
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 546, in unpack_http_url
    resp = session.get(target_url, stream=True)
  File "/usr/share/python-wheels/requests-2.2.1-py2.py3-none-any.whl/requests/sessions.py", line 467, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 237, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/usr/share/python-wheels/requests-2.2.1-py2.py3-none-any.whl/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/share/python-wheels/requests-2.2.1-py2.py3-none-any.whl/requests/sessions.py", line 558, in send
    r = adapter.send(request, **kwargs)
  File "/usr/share/python-wheels/requests-2.2.1-py2.py3-none-any.whl/requests/adapters.py", line 330, in send
    timeout=timeout
  File "/usr/share/python-wheels/urllib3-1.7.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 562, in urlopen
    body=body, headers=headers)
  File "/usr/share/python-wheels/urllib3-1.7.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 1017, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1051, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1013, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 864, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 826, in send
    self.connect()
  File "/usr/share/python-wheels/urllib3-1.7.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 145, in connect
    match_hostname(self.sock.getpeercert(),
  File "/usr/share/python-wheels/urllib3-1.7.1-py2.py3-none-any.whl/urllib3/contrib/pyopenssl.py", line 313, in getpeercert
    for value in get_subj_alt_name(x509)
  File "/usr/share/python-wheels/urllib3-1.7.1-py2.py3-none-any.whl/urllib3/contrib/pyopenssl.py", line 94, in get_subj_alt_name
    asn1Spec=general_names)
  File "/usr/lib/python2.7/dist-packages/pyasn1/codec/ber/decoder.py", line 792, in __call__
    stGetValueDecoder, self, substrateFun
  File "/usr/lib/python2.7/dist-packages/pyasn1/codec/ber/decoder.py", line 370, in valueDecoder
    r.verifySizeSpec()
  File "/usr/lib/python2.7/dist-packages/pyasn1/type/base.py", line 231, in verifySizeSpec
    def verifySizeSpec(self): self._sizeSpec(self)
  File "/usr/lib/python2.7/dist-packages/pyasn1/type/constraint.py", line 32, in __call__
    '%s failed at: \"%s\"' % (self, sys.exc_info()[1])
ValueConstraintError: ConstraintsIntersection(ConstraintsIntersection(), ValueSizeConstraint(1, 64)) failed at: "ValueSizeConstraint(1, 64) failed at: "SubjectAltName().setComponentByPosition(0, GeneralName().setComponentByPosition(1, IA5String('r.ssl.fastly.net'))).setComponentByPosition(1, GeneralName().setComponentByPosition(1, IA5String('*.addthis.com'))).setComponentByPosition(2, GeneralName().setComponentByPosition(1, IA5String('*.addthisedge.com'))).setComponentByPosition(3, GeneralName().setComponentByPosition(1, IA5String('*.adwerx.com'))).setComponentByPosition(4, GeneralName().setComponentByPosition(1, IA5String('*.alittlecraft.com'))).setComponentByPosition(5, GeneralName().setComponentByPosition(1, IA5String('*.alittlecraft.it'))).setComponentByPosition(6, GeneralName().setComponentByPosition(1, IA5String('*.alittlemarket.com'))).setComponentByPosition(7, GeneralName().setComponentByPosition(1, IA5String('*.alittlemarket.it'))).setComponentByPosition(8, GeneralName().setComponentByPosition(1, IA5String('*.alittlemercerie.com'))).setComponentByPosition(9, GeneralName().setComponentByPosition(1, IA5String('*.bighatads.com'))).setComponentByPosition(10, GeneralName().setComponentByPosition(1, IA5String('*.buzzfeed.com'))).setComponentByPosition(11, GeneralName().setComponentByPosition(1, IA5String('*.catchpoint.com'))).setComponentByPosition(12, GeneralName().setComponentByPosition(1, IA5String('*.cnn.io'))).setComponentByPosition(13, GeneralName().setComponentByPosition(1, IA5String('*.corednacdn.com'))).setComponentByPosition(14, GeneralName().setComponentByPosition(1, IA5String('*.dollarshaveclub.com'))).setComponentByPosition(15, GeneralName().setComponentByPosition(1, IA5String('*.domfee.com'))).setComponentByPosition(16, GeneralName().setComponentByPosition(1, IA5String('*.eater.com'))).setComponentByPosition(17, GeneralName().setComponentByPosition(1, IA5String('*.fastlylabs.com'))).setComponentByPosition(18, GeneralName().setComponentByPosition(1, IA5String('*.files.saymedia-content.com'))).setComponentByPosition(19, GeneralName().setComponentByPosition(1, IA5String('*.finncdn.no'))).setComponentByPosition(20, GeneralName().setComponentByPosition(1, IA5String('*.ft.com'))).setComponentByPosition(21, GeneralName().setComponentByPosition(1, IA5String('*.geonet.org.nz'))).setComponentByPosition(22, GeneralName().setComponentByPosition(1, IA5String('*.hipmunkstaging.com'))).setComponentByPosition(23, GeneralName().setComponentByPosition(1, IA5String('*.houselogic.com'))).setComponentByPosition(24, GeneralName().setComponentByPosition(1, IA5String('*.issuu.com'))).setComponentByPosition(25, GeneralName().setComponentByPosition(1, IA5String('*.isu.pub'))).setComponentByPosition(26, GeneralName().setComponentByPosition(1, IA5String('*.jackthreads.com'))).setComponentByPosition(27, GeneralName().setComponentByPosition(1, IA5String('*.lostmy.name'))).setComponentByPosition(28, GeneralName().setComponentByPosition(1, IA5String('*.meetupstatic.com'))).setComponentByPosition(29, GeneralName().setComponentByPosition(1, IA5String('*.netzwelt.de'))).setComponentByPosition(30, GeneralName().setComponentByPosition(1, IA5String('*.nfl.com'))).setComponentByPosition(31, GeneralName().setComponentByPosition(1, IA5String('*.pagar.me'))).setComponentByPosition(32, GeneralName().setComponentByPosition(1, IA5String('*.picmonkey.com'))).setComponentByPosition(33, GeneralName().setComponentByPosition(1, IA5String('*.pypi.io'))).setComponentByPosition(34, GeneralName().setComponentByPosition(1, IA5String('*.pypi.org'))).setComponentByPosition(35, GeneralName().setComponentByPosition(1, IA5String('*.pythonhosted.org'))).setComponentByPosition(36, GeneralName().setComponentByPosition(1, IA5String('*.r29static.com'))).setComponentByPosition(37, GeneralName().setComponentByPosition(1, IA5String('*.realself.com'))).setComponentByPosition(38, GeneralName().setComponentByPosition(1, IA5String('*.rtbf.be'))).setComponentByPosition(39, GeneralName().setComponentByPosition(1, IA5String('*.sbnation.com'))).setComponentByPosition(40, GeneralName().setComponentByPosition(1, IA5String('*.shakr.com'))).setComponentByPosition(41, GeneralName().setComponentByPosition(1, IA5String('*.shiftpreview.com'))).setComponentByPosition(42, GeneralName().setComponentByPosition(1, IA5String('*.static.rtbf.be'))).setComponentByPosition(43, GeneralName().setComponentByPosition(1, IA5String('*.streamable.com'))).setComponentByPosition(44, GeneralName().setComponentByPosition(1, IA5String('*.surfly.com'))).setComponentByPosition(45, GeneralName().setComponentByPosition(1, IA5String('*.theverge.com'))).setComponentByPosition(46, GeneralName().setComponentByPosition(1, IA5String('*.thrillist.com'))).setComponentByPosition(47, GeneralName().setComponentByPosition(1, IA5String('*.tissuu.com'))).setComponentByPosition(48, GeneralName().setComponentByPosition(1, IA5String('*.vox-cdn.com'))).setComponentByPosition(49, GeneralName().setComponentByPosition(1, IA5String('*.vox.com'))).setComponentByPosition(50, GeneralName().setComponentByPosition(1, IA5String('*.voxmedia.com'))).setComponentByPosition(51, GeneralName().setComponentByPosition(1, IA5String('*.w-x.co'))).setComponentByPosition(52, GeneralName().setComponentByPosition(1, IA5String('*.watch.aetnd.com'))).setComponentByPosition(53, GeneralName().setComponentByPosition(1, IA5String('*.wework.com'))).setComponentByPosition(54, GeneralName().setComponentByPosition(1, IA5String('*.wired.com'))).setComponentByPosition(55, GeneralName().setComponentByPosition(1, IA5String('adwerx.com'))).setComponentByPosition(56, GeneralName().setComponentByPosition(1, IA5String('alittlecraft.com'))).setComponentByPosition(57, GeneralName().setComponentByPosition(1, IA5String('alittlecraft.it'))).setComponentByPosition(58, GeneralName().setComponentByPosition(1, IA5String('alittlemarket.com'))).setComponentByPosition(59, GeneralName().setComponentByPosition(1, IA5String('alittlemarket.it'))).setComponentByPosition(60, GeneralName().setComponentByPosition(1, IA5String('alittlemercerie.com'))).setComponentByPosition(61, GeneralName().setComponentByPosition(1, IA5String('alpha.entrepreneur.com'))).setComponentByPosition(62, GeneralName().setComponentByPosition(1, IA5String('api.shiftcommerce.com'))).setComponentByPosition(63, GeneralName().setComponentByPosition(1, IA5String('assets-staging.themuse.com'))).setComponentByPosition(64, GeneralName().setComponentByPosition(1, IA5String('buzzfeed.com'))).setComponentByPosition(65, GeneralName().setComponentByPosition(1, IA5String('dev.api.cerebro.cnn.io'))).setComponentByPosition(66, GeneralName().setComponentByPosition(1, IA5String('dev.historyvault.com'))).setComponentByPosition(67, GeneralName().setComponentByPosition(1, IA5String('dev.lifetimemovieclub.com'))).setComponentByPosition(68, GeneralName().setComponentByPosition(1, IA5String('eater.com'))).setComponentByPosition(69, GeneralName().setComponentByPosition(1, IA5String('entrepreneur.com'))).setComponentByPosition(70, GeneralName().setComponentByPosition(1, IA5String('fastly.shiekhdev.com'))).setComponentByPosition(71, GeneralName().setComponentByPosition(1, IA5String('ft.com'))).setComponentByPosition(72, GeneralName().setComponentByPosition(1, IA5String('h2.hipmunkstaging.com'))).setComponentByPosition(73, GeneralName().setComponentByPosition(1, IA5String('i.gse.io'))).setComponentByPosition(74, GeneralName().setComponentByPosition(1, IA5String('lostmy.name'))).setComponentByPosition(75, GeneralName().setComponentByPosition(1, IA5String('preview.entrepreneur.com'))).setComponentByPosition(76, GeneralName().setComponentByPosition(1, IA5String('pythonhosted.org'))).setComponentByPosition(77, GeneralName().setComponentByPosition(1, IA5String('qa.safariflow.com'))).setComponentByPosition(78, GeneralName().setComponentByPosition(1, IA5String('realself.com'))).setComponentByPosition(79, GeneralName().setComponentByPosition(1, IA5String('rtbf.be'))).setComponentByPosition(80, GeneralName().setComponentByPosition(1, IA5String('ssl.netzwelt.de'))).setComponentByPosition(81, GeneralName().setComponentByPosition(1, IA5String('stag2.wired.com'))).setComponentByPosition(82, GeneralName().setComponentByPosition(1, IA5String('stag3.wired.com'))).setComponentByPosition(83, GeneralName().setComponentByPosition(1, IA5String('stag4.wired.com'))).setComponentByPosition(84, GeneralName().setComponentByPosition(1, IA5String('static.refinery29.com'))).setComponentByPosition(85, GeneralName().setComponentByPosition(1, IA5String('static.wixstatic.com'))).setComponentByPosition(86, GeneralName().setComponentByPosition(1, IA5String('streamable.com'))).setComponentByPosition(87, GeneralName().setComponentByPosition(1, IA5String('surfly.com'))).setComponentByPosition(88, GeneralName().setComponentByPosition(1, IA5String('theverge.com'))).setComponentByPosition(89, GeneralName().setComponentByPosition(1, IA5String('vox-cdn.com'))).setComponentByPosition(90, GeneralName().setComponentByPosition(1, IA5String('vox.com'))).setComponentByPosition(91, GeneralName().setComponentByPosition(1, IA5String('wired.com'))).setComponentByPosition(92, GeneralName().setComponentByPosition(1, IA5String('www.dexigner.com'))).setComponentByPosition(93, GeneralName().setComponentByPosition(1, IA5String('www.entrepreneur.com'))).setComponentByPosition(94, GeneralName().setComponentByPosition(1, IA5String('www.joyent.com'))).setComponentByPosition(95, GeneralName().setComponentByPosition(1, IA5String('www.qa.safariflow.com'))).setComponentByPosition(96, GeneralName().setComponentByPosition(1, IA5String('www.stackpop.com')))""

Storing debug log for failure in /home/atrus/.pip/pip.log```

**Comment by PizzaWaffles** [comment]
That seems to be an issue with the requests and urllib packages. First navigate to your python directory, in dist-packages delete requests and urllib (or move them somewhere). Then run this
`sudo easy_install requests`
`sudo easy_install pip`
