### ISSUE TITLE
An error occurred with running poetry Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by pappabetalar** [Dannyman3819/Automatic-Youtube-Downloader#55]
Hi

I just updated to Ubuntu 20.04 LTS now i am unable to start AYD.

`pappabetalar@BIGubuntu:~/Automatic-Youtube-Downloader-master$ python3 main.py
You need to update your dependencies to continue. Update? (y/n) y
Checking Dependencies....
Python Path: /usr/bin/python3
Retrieving Poetry metadata

Latest version already installed.
Traceback (most recent call last):
  File "/home/pappabetalar/Automatic-Youtube-Downloader-master/poetry/bin/poetry", line 11, in <module>
    from poetry.console import main
  File "/home/pappabetalar/Automatic-Youtube-Downloader-master/poetry/lib/poetry/console/__init__.py", line 1, in <module>
    from .application import Application
  File "/home/pappabetalar/Automatic-Youtube-Downloader-master/poetry/lib/poetry/console/application.py", line 7, in <module>
    from cleo.formatters import Formatter
ModuleNotFoundError: No module named 'cleo.formatters'
An error occurred with running poetry
pappabetalar@BIGubuntu:~/Automatic-Youtube-Downloader-master$
`

**Comment by pappabetalar** [comment]
Fixed this temporarily by creating "py3.8" in this directory /home/pappabetalar/Automatic-Youtube-Downloader-master/poetry/lib/poetry/_vendor/
