### ISSUE TITLE
Channel names with spaces - cannot copy tree not a directory

### ISSUE THREAD

**Issue by mcroot42** [Dannyman3819/Automatic-Youtube-Downloader#8]
Channel names with a space on latest Ubuntu fail to copy after downloading.

Example
`2018-09-01 19:26:14.824944
cannot copy tree 'Download/The Orville - [UC-AtVTn-F0RUtdXDXzhXzmQ]/': not a directoryTraceback (most recent call last):
  File "main.py", line 248, in main
    copy_tree(sourceDir, destinationDir)
  File "/usr/lib/python2.7/distutils/dir_util.py", line 128, in copy_tree
    "cannot copy tree '%s': not a directory" % src
DistutilsFileError: cannot copy tree 'Download/The Orville - [UC-AtVTn-F0RUtdXDXzhXzmQ]/': not a directory`

Adding 
`uploader = uploader.replace(" ", "_")`
at line 204 resolved the issue for me.

**Comment by mcroot42** [comment]
Correction, I better way to fix this is to ensure LC_ALL is set correctly

`export LC_ALL="en_US.UTF-8"`
